create table anotacoes (
    id bigint generated by default as identity primary key,
    titulo varchar(120) not null,
    conteudo text not null,
    criado_em timestamp not null default current_timestamp,
    atualizado_em timestamp not null default current_timestamp
);
