create table usuarios (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    email varchar(180) not null unique,
    senha varchar(100) not null,
    data_nascimento date,
    escolaridade varchar(40),
    perfil varchar(20) not null,
    criado_em timestamp not null default current_timestamp
);

alter table anotacoes add column usuario_id bigint;
alter table anotacoes alter column usuario_id set not null;
alter table anotacoes add constraint fk_anotacoes_usuario
    foreign key (usuario_id) references usuarios(id);
create index idx_anotacoes_usuario on anotacoes(usuario_id);

create table registros_auditoria (
    id bigint generated by default as identity primary key,
    usuario_id bigint references usuarios(id) on delete set null,
    email varchar(180),
    acao varchar(60) not null,
    recurso varchar(255) not null,
    sucesso boolean not null,
    detalhes varchar(500),
    endereco_ip varchar(64),
    user_agent varchar(500),
    criado_em timestamp not null default current_timestamp
);

create index idx_auditoria_usuario_data on registros_auditoria(usuario_id, criado_em desc);
