create table versoes_anotacao (
    id bigint generated by default as identity primary key,
    anotacao_id bigint not null references anotacoes(id) on delete cascade,
    tipo varchar(20) not null,
    conteudo text not null,
    criado_em timestamp not null default current_timestamp
);

insert into versoes_anotacao (anotacao_id, tipo, conteudo, criado_em)
select id, 'ORIGINAL', conteudo, criado_em
from anotacoes;
