create table codigos_autenticacao (
    id bigint generated by default as identity primary key,
    desafio_id uuid not null unique,
    usuario_id bigint not null references usuarios(id) on delete cascade,
    codigo_hash varchar(100) not null,
    tentativas integer not null default 0,
    expira_em timestamp not null,
    usado_em timestamp,
    criado_em timestamp not null default current_timestamp
);

create index idx_codigos_usuario_data on codigos_autenticacao(usuario_id, criado_em desc);
create index idx_codigos_expiracao on codigos_autenticacao(expira_em);
